let what = ["who", "where", "when"];
let what1 = what.push("how");
console.log(what1);
console.log(what);
let what2 = what.push("que");
console.log(what2);
console.log(what);
let what3 = what.pop();
console.log(what3);
console.log(what);
let what4 = what.push("noSay");
console.log(what4);
console.log(what);
let what5 = what.pop();
console.log(what5);
console.log(what);
let what6 = what.push("howCome");
let what7 = what.push("whatThe");
console.log(what6);
console.log(what7);
console.log(what);
let what8 = what.pop();
let what9 = what.push("porQue");
console.log(what8);
console.log(what9);
console.log(what);
const what10 = what.push("getTheFuckOuttaHere");
console.log(what10);
console.log(what);
let bs = what.push("confusing");
console.log(bs);
console.log(what);
let ass = what.push("big");
console.log(ass);
console.log(what);
let bigAss = ["huge", "round", "plump", "thick"];
console.log(bigAss);
let booty = bigAss.push("bouncy");
console.log(booty);
console.log(bigAss);
let dumper = bigAss.push("curvy");
console.log(dumper);
console.log(bigAss);
const dumperDown = bigAss.push("grandular");
console.log(dumperDown);
console.log(bigAss);
let small = bigAss.pop();
console.log(small);
console.log(bigAss);